# Simple debug build. Requires OpenCV2 lib, therefore
# this job can only be performed by runners with the
# "opencv2" tag
build:
  script:
    - mkdir build/
    - cd build
    - cmake -D CMAKE_BUILD_TYPE=Debug ..
    - make
  tags:
    - cmake
    - opencv2
    - gcc

# Building with Visual Studio 12 2013
# Loads the OpenCV directory from the environmetal variable "OpenCV_DIR"
build-visual-studio:
  script:
    - mkdir build
    - cd build
    - cmake -G "Visual Studio 12 Win64" -D CMAKE_BUILD_TYPE=Debug ..
    - cmake --build .
  tags:
    - opencv2
    - windows
    - cmake
    - visual-studio
