# Special build for Windows
build-win:
  script:
    - mkdir build
    - cd build
    # Load the OpenCV directory from the environmetal variable "OpenCV_DIR"
    - cmake -G "MinGW Makefiles"
        -D CMAKE_BUILD_TYPE=Debug
        -D CMAKE_CXX_COMPILER=mingw32-g++.exe
        -D OpenCV_DIR=%OpenCV_DIR%
        MAKE_MAKE_PROGRAM=mingw32-make.exe ..
    - mingw32-make.exe
  tags:
    - opencv2
    - windows
    - cmake
    - mingw