# Simple debug build. Requires OpenCV2 lib, therefore
# this job can only be performed by runners with the
# "opencv2" tag
build:
  script:
    - mkdir build/
    - cd build
    - cmake -D CMAKE_BUILD_TYPE=Debug ..
    - make
  tags:
    - opencv2
