# Simple debug build. Requires OpenCV2 lib, therefore
# this job can only be performed by runners with the
# "opencv2" tag
build:
  script:
    - mkdir build/
    - cd build
    - cmake -D CMAKE_BUILD_TYPE=Debug ..
    - make
  tags:
    - cmake
    - opencv2

# Force usage of our custom getopt implementation
build-getopt:
  script:
    - mkdir build/
    - cd build
    - cmake -D CMAKE_BUILD_TYPE=Debug -D FORCE_GETOPT=ON ..
    - make
  tags:
    - cmake
    - opencv2

# Special build for Windows
# Loads the OpenCV directory from the environmetal variable "OpenCV_DIR"
build-win:
  script:
    - mkdir build
    - cd build
    - cmake -G "MinGW Makefiles" -D CMAKE_BUILD_TYPE=Debug -D CMAKE_CXX_COMPILER=g++ MAKE_MAKE_PROGRAM=mingw32-make ..
    - cmake --build .
  tags:
    - opencv2
    - windows
    - cmake
    - mingw

# Force usage of our custom getopt implementation
build-getopt-win:
  script:
    - mkdir build
    - cd build
    - cmake -G "MinGW Makefiles" -D CMAKE_BUILD_TYPE=Debug -D FORCE_GETOPT=ON -D CMAKE_CXX_COMPILER=g++ MAKE_MAKE_PROGRAM=mingw32-make ..
    - cmake --build .
  tags:
    - opencv2
    - windows
    - cmake
    - mingw
